# Generated by Django 4.1.7 on 2023-03-08 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('todo_id', models.AutoField(primary_key=True, serialize=False)),
                ('todo_title', models.CharField(max_length=50)),
                ('todo_time', models.TimeField(verbose_name=django.utils.timezone.now)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
