# Generated by Django 4.1.7 on 2023-03-08 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='todo_time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 8, 14, 5, 3, 780643, tzinfo=datetime.timezone.utc)),
        ),
    ]
