# Generated by Django 4.1.7 on 2023-03-08 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_todoitem_todo_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='is_done',
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='todo_time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 8, 15, 49, 4, 294376, tzinfo=datetime.timezone.utc)),
        ),
    ]
