# Generated by Django 4.1.7 on 2023-03-09 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_alter_todoitem_todo_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='todo_time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 9, 12, 52, 21, 271037, tzinfo=datetime.timezone.utc)),
        ),
    ]
