# Generated by Django 4.1.7 on 2023-03-09 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_alter_todoitem_todo_time_alter_todoitem_todo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='todo_time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 9, 12, 53, 36, 818651, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
